export const dummy = [
  {
    id: 0,
    image: require("./Assets/sample3.webp"),
    title: "MECH 261: 2ND LAW OF THERMODYNAMICS",
    price: "1700",
    tags: "1st Semester",
    smallimage: require("./Assets/small.png"),
    department: "computer science",

    discount: "5545",
    faculty: "general",
    tutor: "Emmanuel",
  },
  {
    id: 1,
    image: require("./Assets/sample1.webp"),
    title: "PHY 191 workbook",
    price: "1700",
    tags: "1st Semester",
    smallimage: require("./Assets/sample1.webp"),
    department: "computer science",

    discount: "3444",
    faculty: "Physical Sciences",
    tutor: "Emmanuel",
  },
  {
    id: 2,
    image: require("./Assets/sample1.webp"),
    title: "MECH 261: 2ND LAW OF THERMODYNAMICS",
    price: "1700",
    discount: "3444",
    tags: "1st Semester",
    smallimage: require("./Assets/sample1.webp"),
    department: "computer science",

    faculty: "Physical Sciences",
    tutor: "Emmanuel",
  },
  {
    id: 3,
    image: require("./Assets/sample3.webp"),
    title: "PCL 353",
    price: "1700",
    discount: "3444",
    tags: "1st Semester",
    smallimage: require("./Assets/sample1.webp"),
    department: "computer science",
    faculty: "Pharmacy",
    tutor: "Emmanuel",
  },
  {
    id: 4,
    image: require("./Assets/sample1.webp"),
    title: "MECH 261: 2ND LAW OF THERMODYNAMICS",
    price: "1700",
    discount: "3444",
    faculty: "Pharmacy",
    tags: "1st Semester",
    smallimage: require("./Assets/sample1.webp"),
    department: "computer science",

    tutor: "Emmanuel",
  },
  {
    id: 5,
    image: require("./Assets/sample1.webp"),
    title: "PCL 353",
    tags: "1st Semester",
    smallimage: require("./Assets/sample1.webp"),
    department: "computer science",

    price: "1700",
    discount: "3444",
    faculty: "Pharmacy",
    tutor: "Emmanuel",
  },
];
